# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elevenlabs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'elevenlabs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65levenlabs.proto\x12\nelevenlabs\"q\n\x1aStreamingSynthesizeRequest\x12$\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x12.elevenlabs.ConfigH\x00\x12\"\n\x05input\x18\x02 \x01(\x0b\x32\x11.elevenlabs.InputH\x00\x42\t\n\x07request\"C\n\x06\x43onfig\x12\x10\n\x08voice_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x15\n\routput_format\x18\x03 \x01(\t\"\x15\n\x05Input\x12\x0c\n\x04text\x18\x01 \x01(\t\"2\n\x1bStreamingSynthesizeResponse\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x32|\n\x0cTextToSpeech\x12l\n\x13StreamingSynthesize\x12&.elevenlabs.StreamingSynthesizeRequest\x1a\'.elevenlabs.StreamingSynthesizeResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elevenlabs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINGSYNTHESIZEREQUEST']._serialized_start=32
  _globals['_STREAMINGSYNTHESIZEREQUEST']._serialized_end=145
  _globals['_CONFIG']._serialized_start=147
  _globals['_CONFIG']._serialized_end=214
  _globals['_INPUT']._serialized_start=216
  _globals['_INPUT']._serialized_end=237
  _globals['_STREAMINGSYNTHESIZERESPONSE']._serialized_start=239
  _globals['_STREAMINGSYNTHESIZERESPONSE']._serialized_end=289
  _globals['_TEXTTOSPEECH']._serialized_start=291
  _globals['_TEXTTOSPEECH']._serialized_end=415
# @@protoc_insertion_point(module_scope)
